name: cov_utils
description: A set of commands for coverage info files manipulation.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.2.0
  collection: ^1.15.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.17.12
  very_good_analysis: ^2.3.0

executables:
  x:
  cov:
